from classes.user_repository.repository import UserRepository
from classes.user_repository.mutations.user_preferences import UserPreferenceMutations

UserRepository.init_user()
UserPreferenceMutations._drop_blacklist()
UserPreferenceMutations._drop_shortlist()
